/* import { Header } from '@/components/Header/Header'; */
import { MainTemplate } from '@/templates/MainTemplate';

export const Home = (): React.JSX.Element => {
  return (
    <MainTemplate>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>ESTOU NA HOME HEHEHE</div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
      <div>
        ESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA
        HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEvESTOU NA HOME
        HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU NA HOME HEHEHEESTOU
        NA HOME HEHEHEESTOU NA HOME HEHEHE
      </div>
    </MainTemplate>
  );
};
